### ISSUE TITLE
一处改动

### ISSUE THREAD

**Issue by SennriSyunnga** [y2361547758/bcc2ass#1]
`        with open(args.bcc_file) as f: bcc=json.load(f)`
`        with open(args.bcc_file，'r',encoding='UTF-8') as f: bcc=json.load(f)#New version！`
        刚学python，之前这段过不去，把except注释掉看了看是这个问题。指明格式就不会报错了。估计是电脑的解码器默认得不一致吧。

**Comment by y2361547758** [comment]
大概是因为我把win10的默认编码改成utf8了
