### ISSUE TITLE
Issue with .ass lining

### ISSUE THREAD

**Issue by ghost** [y2361547758/bcc2ass#2]
```
Dialogue: 0,0:01:24.33,0:01:25.54,Default,,0,0,0,,-How is it?
-Is this good?
```
The ass line separate like this when working with "\n" but not the case for srt

**Comment by zhongfly** [comment]
https://github.com/y2361547758/bcc2ass/blob/master/bcc2ass.py#L49
`print("Dialogue: 0," + sec2time(i['from'], type) + "," + sec2time(i['to'], type) + ",Default,,0,0,0,," + align + i['content'].replace('\n',r'\N'), file=f)`
